export const dummydata = [
  {
    id: 1,
    collectionname: "Crypto Punks",
    title: "this is the first Agenda",
    content: "I really wonna money so need to sell",
    address: "0x132...256",
    type: "sell",
    profile: "profile.jpg",
  },
  {
    id: 2,
    collectionname: "Crypto Punks",
    title: "I need a money ... wanna money",
    content: "Yes i agree",
    address: "0x132...256",
    type: "sell",
    profile: "gallery3.jpg",
  },
  {
    id: 3,
    collectionname: "Bored Ape Yacht Club",
    title: "I need a money ... wanna money",
    content: "I really wonna money so need to sell",
    address: "0x132...256",
    type: "sell",
    profile: "ranking.jpg",
  },
  {
    id: 4,
    collectionname: "Bored Ape Yacht Club",
    title: "I need a money ... wanna money",
    content: "I really wonna money so need to sell",
    address: "0x132...256",
    type: "sell",
    profile: "gallery1.jpg",
  },
  {
    id: 5,
    collectionname: "Mustant Ape Yacht Club",
    title: "I want to sell",
    content: "I really wonna money so need to sell",
    address: "0x132...256",
    type: "sell",
    profile: "gallery1.jpg",
  },
  {
    id: 6,
    collectionname: "Mustant Ape Yacht Club",
    title: "I want to staking",
    content: "I really wonna money so need to sell",
    address: "0x132...256",
    type: "staking",
    profile: "gallery1.jpg",
  },
];
